# Generated by Django 4.2.4 on 2023-10-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=255)),
                ('codigo_articulo', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=100)),
                ('cantidad_unidades', models.PositiveIntegerField()),
                ('costo_unitario_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_envio_usd', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
