# Generated by Django 4.2.4 on 2023-10-04 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.simulacion')),
            ],
        ),
    ]
