# Generated by Django 4.2.4 on 2023-10-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_historialconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='costo_envio_clp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='costo_total_compra_clp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='iva_clp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='tasa_aduana_clp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='total_impuestos_aduana_clp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='total_pedido_clp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
